source 'https://github.com/CocoaPods/Specs.git'

platform :ios, "8.0"

use_frameworks!

pod "Alamofire", "~> 3.0" # 网络请求

#pod "MagicalRecord" # 数据库

pod "SwiftyJSON" # JSON

pod "IQKeyboardManagerSwift" # 键盘

pod "SlideMenuControllerSwift" # 侧滑菜单

pod "MBProgressHUD", "~> 0.9.2" # 等待提示

pod "CocoaAsyncSocket" # Socket

pod 'MJRefresh' # 刷新控件

pod 'ZXingObjC' # 二维码扫描
